config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'parks#index'

  resources :users

  resources :users do
    get 'admin_edit'
  end

  resources :parks do
    resources :reviews
  end

  resources :parks do
    post 'upvote'
    post 'downvote'
  end

  resources :reviews do
    post 'upvote'
    post 'downvote'
  end

  namespace :api do
    namespace :v1 do
      resources :review_votes do
        post 'upvote'
        post 'downvote'
      end
    end
  end

end

app/models/park.rb
class Park < ApplicationRecord
  mount_uploader :main_image, ParkPictureUploader

  belongs_to :user
  has_many :reviews, :dependent => :delete_all
  has_many :park_votes, :dependent => :delete_all
  has_many :review_votes, :dependent => :delete_all

  has_many :park_forecasts

  validates :name, presence: true, uniqueness: { message: " - This park has already been created." }
  validates :main_image, presence: true

  STATES = [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
    "US Territories",
  ]

  ABBREVIATIONS = [
    "AL",
    "AK",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "FL",
    "GA",
    "HI",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "MN",
    "NB",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VM",
    "VA",
    "WA",
    "WV",
    "WI",
    "WY",
    "USA",
  ]

  def calculate_score
    if !self.park_votes.empty?
      return self.park_votes.inject(0){|sum, vote| sum + vote.choice }
    else
      return 0
    end
  end

  def state_abbreviation
    Park::ABBREVIATIONS[ Park::STATES.index(self.state) ]
  end

end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  before_action :authorize_sign_in, only: [:upvote, :downvote]
  before_action :authorize_edit, only: [:edit, :update, :destroy]

  def index
    if params[:search_terms]
      ActiveRecord::Base.connection.execute("SELECT set_limit(0.15);")
      @parks = Park.fuzzy_search(params[:search_terms]).page params[:page]
      if Park.fuzzy_search(params[:search_terms]).empty?
        flash.now[:notice] = "No results found for #{params[:search_terms]}."
      end
    else
      @parks = Park.order("name").page params[:page]
    end
    recent_data
  end

  def show
    @park = Park.find(params[:id])
    @creator_name = @park.user.display_name
    @reviews = Review.where(park_id: params[:id]).order('created_at DESC')
    @review_id_list = @reviews.map { |review| review.id }
    recent_data # for displaying on side bar

    # this will display the forecast div if the weather has been updated
    if !@park.park_forecasts.empty?
      @display_weather = true
      @forecast = @park.park_forecasts.last
      @simple_forecast = @forecast.simple_forecasts
    else
      @display_weather = false
    end

  end

  def new
    @park = Park.new
    @state_collection = Park::STATES
    recent_data
  end

  def edit
    @park = Park.find(params[:id])
    @state_collection = Park::STATES
    recent_data
  end

  def create
    @park = Park.new(park_params)
    @park.user_id = current_user.id

    if @park.save
      flash[:notice] = "#{@park.name} created!"
      redirect_to park_path(@park)
    else
      flash[:alert] = "New park not created"
      @state_collection = Park::STATES
      render :new
    end
  end

  def update
    @park = Park.find(params[:id])

    if @park.update(park_params)
      flash[:notice] = "#{@park.name} updated."
      redirect_to park_path(@park)
    else
      flash[:alert] = "Update failed"
      @state_collection = Park::STATES
      render :edit
    end
  end

  def destroy
    @park = Park.find(params[:id])
    @park.destroy
    redirect_to parks_path
  end

  def upvote
    @park = Park.find(params[:park_id])
    @vote = ParkVote.where(park_id: params[:park_id], user_id: current_user.id)[0]

    if @vote.nil?
      ParkVote.create(choice: 1, park_id: @park.id, user_id: current_user.id)
      redirect_to park_path(@park)
    elsif @vote.choice == 1
      @vote.choice = 0
      @vote.save
      redirect_to park_path(@park)
    else
      @vote.choice = 1
      @vote.save
      redirect_to park_path(@park)
    end
  end

  def downvote
    @park = Park.find(params[:park_id])
    @vote = ParkVote.where(park_id: params[:park_id], user_id: current_user.id)[0]

    if @vote.nil?
      ParkVote.create(choice: -1, park_id: @park.id, user_id: current_user.id)
      redirect_to park_path(@park)
    elsif @vote.choice == -1
      @vote.choice = 0
      @vote.save
      redirect_to park_path(@park)
    else
      @vote.choice = -1
      @vote.save
      redirect_to park_path(@park)
    end
  end

  private

  def park_params
    params.require(:park).permit(:name, :main_image, :state, :year_founded, :area_miles)
  end

  def authorize_sign_in
    if !user_signed_in?
      render file: "#{Rails.root}/public/404.html", layout: false, status: 404
    end
  end

  def authorize_edit
    if current_user
      if current_user.id != Park.find(params[:id]).user_id && !current_user.admin?
        render file: "#{Rails.root}/public/404.html", layout: false, status: 404
      end
    else
      render file: "#{Rails.root}/public/404.html", layout: false, status: 404
    end
  end

end

app/helpers/parks_helper.rb
module ParksHelper
end

app/views/parks/_form.html.erb
<%= form_for(@park) do |f| %>

  <% if @park.errors.any? %>
      <div id="new-park-error">
        <h2><%= pluralize(@park.errors.count, "error") %> in park creation:</h2>

        <ul>
        <% @park.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

  <%= f.label :name, "Park Name" %>
  <%= f.text_field :name %><br>

  <%= f.label :state, "State" %>
  <%= f.select :state, @state_collection %><br>

  <%= f.label :main_image, "Park Image" %>
  <%= f.file_field :main_image %><br>
    <% if f.object.main_image? %>
    <%= image_tag f.object.main_image.thumb.url %>
  <% end %><br>


  <%= f.label :year_founded, "Year Founded" %><em> (optional)</em>
  <%= f.text_field :year_founded %><br>
  <%= f.label :area_miles, "Area in sq miles" %><em> (optional)</em>
  <%= f.number_field :area_miles %><br>

  <%= f.submit 'Submit' %>

<% end %>

app/views/parks/_full_park_info.html.erb
<div class="full-park-info">
  <h3><%= @park.name %><br><small>  <%= @park.state %></small></h3>

  <div class="park-display">
    <%= image_tag @park.main_image, class: "park-display-image" %>
  </div>


  <div class="callout">
    <ul class="menu simple">
      <% if !current_user.nil? %>
        <% if current_user.id == @park.user_id || current_user.admin? %>
          <li><%= link_to "Edit Park", edit_park_path(@park) %></li>
        <% end %>
        <% if current_user.admin? %>
          <li>
            <%= link_to "Delete Park", @park,
              method: :delete, data: { confirm: "Are you sure you want to delete the following park:\n #{@park.name}" } %>
          </li>
        <% end %>
      <% end %>
    </ul>

    <ul class="menu simple">
      <% if !@park.year_founded.nil? %>
        <li>Year Founded: <%= @park.year_founded %></li>
      <% end %>
      <% if !@park.area_miles.nil? %>
        <li>Area (miles<sup>2</sup>): <%= @park.area_miles %></li>
      <% end %>

      <% if user_signed_in? %>
        <li><small>Submitted By: <%= link_to "#{@park.user.display_name}", user_path(@park.user) %></small></li>
      <% else %>
        <li><small>Submitted By: <%= "#{@park.user.display_name}" %></small></li>
      <% end %>

    </ul>

    <% if !@park.nps_description.nil? %>
      <div class="callout nps-description">
        <p>
          <%= @park.nps_description %>
        </p>
        <small>from NPS.gov</small>
      </div>
    <% end %>

  </div>

</div>

app/views/parks/_park_display.html.erb
<div class="blog-post">
  <h3><%= link_to "#{park.name}", park_path(park) %> <br><small>  <%= park.state %></small></h3>

  <div class="park-display">
    <a href="<%= "parks/#{park.id}" %>"><%= image_tag park.main_image, class: "park-display-image" %></a>
  </div>

  <div class="callout">
    <ul class="menu simple">
      <% if !current_user.nil? %>
        <% if current_user.id == park.user_id || current_user.admin? %>
          <li><%= link_to "Edit Park", edit_park_path(park) %></li>
        <% end %>
        <% if current_user.admin? %>
          <li>
            <%= link_to "Delete Park", park,
              method: :delete, data: { confirm: "Are you sure you want to delete the following park:\n #{park.name}" } %>
          </li>
        <% end %>
      <% end %>
    </ul>

    <ul class="menu simple">
      <% if !park.reviews.empty? %>
        <li>Reviews: <%= park.reviews.length %></li>
        <li>Last Reviewed: <%= park.reviews.last.created_at.strftime "%m/%d/%Y at %l:%M%P" %></li>
      <% else %>
        <li>Reviews: -</li>
      <% end %>
    </ul>

  </div>
  <br>
</div>

app/views/parks/_park_index_display.html.erb
<div class="blog-post">
  <h3><%= link_to "#{park.name}", park_path(park) %> <br><small>  <%= park.state %></small></h3>

  <div class="park-display">
    <a href="<%= "parks/#{park.id}" %>"><%= image_tag park.main_image, class: "park-display-image" %></a>
  </div>

  <div class="callout">
    <ul class="menu simple">
      <% if !current_user.nil? %>
        <% if current_user.id == park.user_id || current_user.admin? %>
          <li><%= link_to "Edit Park", edit_park_path(park) %></li>
        <% end %>
        <% if current_user.admin? %>
          <li>
            <%= link_to "Delete Park", park,
              method: :delete, data: { confirm: "Are you sure you want to delete the following park:\n #{park.name}" } %>
          </li>
        <% end %>
      <% end %>
    </ul>

    <ul class="menu simple">
      <% if !park.reviews.empty? %>
        <li>Reviews: <%= park.reviews.length %></li>
        <li>Last Reviewed: <%= park.reviews.last.created_at.strftime "%m/%d/%Y at %l:%M%P" %></li>
      <% else %>
        <li>Reviews: -</li>
      <% end %>
    </ul>

  </div>
  <br>
</div>

app/views/parks/edit.html.erb
<h1>Edit listing for <%= @park.name %></h1>

<%= render 'form' %>

app/views/parks/index.html.erb
<div class="index-display">
  <%= render partial: "park_index_display", collection: @parks, as: :park %>
</div>

<%= paginate @parks, class: "pagination"%>

app/views/parks/new.html.erb
<h1>Add a new National Park</h1>

<%= render 'form' %>

app/views/parks/show.html.erb
<%= render "full_park_info" %>

<% if @display_weather %>
  <%= render "park_forecasts/park_3_day_forecast" %>
<% end %>

<% if user_signed_in? %>
  <%= javascript_tag do %>
    window.user_id = <%= current_user.id %>;
    window.park_id = <%= @park.id %>;
    window.review_id_list = <%= @review_id_list %>;
  <% end %>
<% end %>

<div class="reviews">
  <h3>Member Reviews (<%= @park.reviews.length %>)
    <% if !current_user.nil?%>
      - <%= link_to "Write a Review", new_park_review_path(@park) %>
    <% end %></h3>
  <%= render partial: "reviews/review_display", collection: @reviews, as: :review %>
</div>