config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'parks#index'

  resources :users

  resources :users do
    get 'admin_edit'
  end

  resources :parks do
    resources :reviews
  end

  resources :parks do
    post 'upvote'
    post 'downvote'
  end

  resources :reviews do
    post 'upvote'
    post 'downvote'
  end

  namespace :api do
    namespace :v1 do
      resources :review_votes do
        post 'upvote'
        post 'downvote'
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  validates_processing_of :avatar
  validate :avatar_size_validation

  validates :display_name, length: { minimum: 5 }, uniqueness: true
  validates :display_name, format: { with: /\A[a-zA-Z0-9\-_]{5,40}\Z/, message: "Only allows letters and numbers" }

  has_many :parks, :dependent => :delete_all
  has_many :reviews, :dependent => :delete_all
  has_many :park_votes, :dependent => :delete_all
  has_many :review_votes, :dependent => :delete_all
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable #,:rememberable
  # validates :display_name, allow_blank: true

  def admin?
    return self.role == "admin"
  end

  private

  def avatar_size_validation
    errors[:avatar] << "should be less than 500KB" if avatar.size > 0.5.megabytes
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_sign_in
  before_action :authorize_admin, only: [:index, :admin_edit, :admin_update]
  before_action :authorize_edit, only: [:edit, :update, :destroy]

  DEFAULT_AVATAR = "https://s3.amazonaws.com/national-park-reviews-development/uploads/avatars/default_avatar.jpg"

  def index
    @users = User.all.order(:id)
  end

  def show
    @user = User.find(params[:id])
    @parks = @user.parks
    @reviews = @user.reviews
    @default = DEFAULT_AVATAR
  end

  def edit
    @user = User.find(params[:id])
    @default = DEFAULT_AVATAR
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:notice] = "Account details updated."
      redirect_to user_path(@user)
    else
      flash[:alert] = "That image is too large. Avatars must be smaller than 500kb."
      render :edit
    end
  end

  def admin_edit
    @user = User.find(params[:user_id])
  end

  def destroy
    binding.pry
  end

  private

  def user_params
    params.require(:user).permit(
      :email,
      :password,
      :display_name,
      :avatar,
      :remove_avatar
    )
  end

  def authorize_sign_in
    if !user_signed_in?
      render file: "#{Rails.root}/public/404.html", layout: false, status: 404
    end
  end

  def authorize_admin
    if !current_user.admin?
      render file: "#{Rails.root}/public/404.html", layout: false, status: 404
    end
  end

  def authorize_edit
    if !current_user.admin? && current_user.id != params[:id].to_i
      render file: "#{Rails.root}/public/404.html", layout: false, status: 404
    end
  end

end

app/views/users/admin_edit.html.erb
<h3>Edit Account Information for <%= @user.display_name %></h3>

<%= form_for(@user, action: "admin_update" ) do |f| %>
  <div class="field">
    <%= f.label :display_name, "Display Name" %> <i>(minimum of 5 characters, no spaces)</i><br />
    <%= f.text_field :display_name %>
  </div>

  <% if @user.avatar.url == @default %>
    <h5>No user avatar provided</h5>
  <% elsif f.object.avatar? && @user.errors.empty? %>
    <%= image_tag f.object.avatar.thumb.url %>
  <% end %>

  <%= f.label :avatar, "User Avatar" %><em> (Max size: 500kb)</em><br>
  <%= f.file_field :avatar %><br>
  <%= f.label :remove_avatar, "Remove avatar?" %>
  <%= f.check_box :remove_avatar %>

  <br><br>

  <%= f.submit 'Submit' %>

<% end %>

app/views/users/edit.html.erb
<h1>Edit Account Information</h1>

<%= form_for(@user) do |f| %>
  <%= f.label :display_name, "Display Name" %>
    <em> (Leave blank to remove)</em><br>
  <%= f.text_field :display_name %><br><br>

  <%= f.label :avatar, "User Avatar" %><em> (Max size: 500kb)</em><br>
  <%= f.file_field :avatar %><br>
  <%= f.label :remove_avatar, "Remove avatar?" %>
  <%= f.check_box :remove_avatar %><br>
    <% if f.object.avatar? && @user.errors.empty? %>
    <%= image_tag f.object.avatar.thumb.url %>
  <% end %>

  <br><br>

  <%= f.submit 'Submit' %>

<% end %>

app/views/users/index.html.erb
<h3>All Registered Users</h3>
<ul>
  <% @users.each do |user| %>
    <li><%= link_to "#{user.email}", user_path(user) %>, as <em><%= user.display_name %></em></li>
    <ul class="menu simple">
      <li><%= link_to "Edit Account", user_admin_edit_path(user) %></li>
      <li><%= link_to "Delete Account", registration_path(user),
        data: { confirm: "Are you sure you want to delete #{user.display_name}?" }, method: :delete %></li>
    </ul>
  <% end %>
</ul>

app/views/users/show.html.erb
<h3><%= @user.display_name %>'s details</h3>
<%= image_tag @user.avatar.thumb, class: "avatar-thumb" %><br>


<% if current_user.id == @user.id || current_user.admin? %>
  <%= link_to "Manage Account Details", edit_user_registration_path %><br>
  <%= link_to "Modify User Avatar", edit_user_path(@user) %><br><br>
<% end %>
<% if current_user.admin? %>
  <%= link_to "Administrator Management", user_admin_edit_path(@user) %><br><br>
<% end %>

<h3>Submitted Parks</h3>
<ul>
  <% @parks.each do |park| %>
    <li><%= link_to "#{park.name}", park_path(park) %></li>
  <% end %>
</ul>

<h3>Submitted Reviews</h3>
<ul>
  <% @reviews.each do |review| %>
    <li>
      <%= link_to "#{review.park.name}", park_path(review.park) %><br>
      <%= review.title %>
    </li>
  <% end %>
</ul>