config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'parks#index'

  resources :users

  resources :users do
    get 'admin_edit'
  end

  resources :parks do
    resources :reviews
  end

  resources :parks do
    post 'upvote'
    post 'downvote'
  end

  resources :reviews do
    post 'upvote'
    post 'downvote'
  end

  namespace :api do
    namespace :v1 do
      resources :review_votes do
        post 'upvote'
        post 'downvote'
      end
    end
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authorize_sign_in
  before_action :authorize_edit, only: [:edit, :update, :destroy]
  respond_to :html, :js

  def new
    @park = Park.find(params[:park_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.park_id = params[:park_id]
    @park = Park.find(params[:park_id])

    if @review.save
      flash[:notice] = "Review created!"
      redirect_to park_path(@park)
    else
      flash[:alert] = "New review not created"
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
    @park = Park.find(params[:park_id])
  end

  def update
    @park = Park.find(params[:park_id])
    @review = Review.find(params[:id])
    @review.update(review_params)
    if @review.save
      flash[:notice] = "Review successfully updated."
      redirect_to park_path(@park)
    else
      flash[:alert] = "Review update failed."
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @park = Park.find(params[:park_id])
    @review.destroy
    redirect_to park_path(@park)
  end

  def upvote
    @review = Review.find(params[:review_id])
    @vote = ReviewVote.where(review_id: @review.id, user_id: current_user.id)[0]

    if @vote.nil?
      ReviewVote.create(choice: 1, review_id: @review.id, user_id: current_user.id, park_id: @review.park.id)
      redirect_to park_path(@review.park)
    elsif @vote.choice == 1
      @vote.choice = 0
      @vote.save
      redirect_to park_path(@review.park)
    else
      @vote.choice = 1
      @vote.save
      redirect_to park_path(@review.park)
    end
  end

  def downvote
    @review = Review.find(params[:review_id])
    @vote = ReviewVote.where(review_id: @review.id, user_id: current_user.id)[0]

    if @vote.nil?
      ReviewVote.create(choice: -1, review_id: @review.id, user_id: current_user.id, park_id: @review.park.id)
      redirect_to park_path(@review.park)
    elsif @vote.choice == -1
      @vote.choice = 0
      @vote.save
      redirect_to park_path(@review.park)
    else
      @vote.choice = -1
      @vote.save
      redirect_to park_path(@review.park)
    end
  end

  private

  def review_params
    params.require(:review).permit(
      :title,
      :body,
      :visit_date
    )
  end

  def authorize_sign_in
    if !user_signed_in?
      render file: "#{Rails.root}/public/404.html", layout: false, status: 404
    end
  end

  def authorize_edit
    review_to_edit = Review.where(id: params[:id])[0]
    if !current_user.admin? && !current_user.reviews.include?(review_to_edit)
      render file: "#{Rails.root}/public/404.html", layout: false, status: 404
    end
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for([@park, @review]) do |f| %>

  <% if @review.errors.any? %>
    <div id="new-review-error">
      <h2><%= pluralize(@review.errors.count, "error") %> prevented your review from being saved:</h2>
      <ul>
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :title, "Review Title" %><br>
  <%= f.text_field :title %><br><br>

  <%= f.label :body, "Your Review" %><br>
  <%= f.text_area :body %><br><br>

  <%= f.label :visit_date, "Date of Visit" %><br>
  <%= f.date_select :visit_date, start_year: 1900, end_year: Time.now.year %><br><br>

  <%= f.submit "Submit Review" %>

<% end %>

app/views/reviews/_review_display.html.erb
<div class="callout comment-container ">

    <div class="review-author-picture medium-2 columns">
      <%= image_tag review.user.avatar, class: "avatar-thumb" %>
    </div>
    <div class="review-info-container medium-10 columns">
      <strong><%= review.title %></strong><br>
      <% if user_signed_in? %>
        By: <%= link_to "#{review.user.display_name}", user_path(review.user) %>
      <% else %>
        By: <%= "#{review.user.display_name}" %>
      <% end %>
      <br><%= review.visit_date.strftime "Date of Visit: %m/%d/%Y" %>
    </div>

    <div class="comment-section-text">
      <p>
        <%= review.body %>
      </p>
    </div>

    <% if !current_user.nil? %>
      <div class="review-voting-container">
        <div class="review_score" >
          <ul class="menu simple">
            <li><p id="review_score_<%=  "#{review.id}" %>" >Review Score: <%= review.calculate_score %></li>
            <li><%= button_to "⇑", review_upvote_path(review), method: :post, class: "upvote-arrow button", id: "upvote_#{review.id}", review_id: "#{review.id}" %></li>
            <li><%= button_to "⇓", review_downvote_path(review), method: :post, class: "downvote-arrow button", id: "downvote_#{review.id}", review_id: "#{review.id}" %></li>
            </p>
          </ul>
        </div>
      </div>
      <% end %>

  <div class="review-controls">
    <ul class="menu simple">
      <li><small><%= review.created_at.strftime "posted on: %m/%d/%Y" %></small></li>

      <% if !current_user.nil? %>
        <% if current_user.admin? || review.user == current_user %>
          <li><%= link_to "Edit Review", edit_park_review_path(@park, review) %></li>
          <li><%= link_to "Delete Review", [@park, review],
            method: :delete, data: { confirm: "Are you sure you want to delete the following review:\n #{review.title}" } %></li>
        <% end %>
      <% end %>

    </ul>
  </div>
</div>

<br>

app/views/reviews/edit.html.erb
<h1>Revise the review for <%= @park.name %></h1>

<%= render 'form' %>

app/views/reviews/new.html.erb
<h1>New Review for <%= @park.name %></h1>

<%= render 'form' %>