config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'parks#index'

  resources :users

  resources :users do
    get 'admin_edit'
  end

  resources :parks do
    resources :reviews
  end

  resources :parks do
    post 'upvote'
    post 'downvote'
  end

  resources :reviews do
    post 'upvote'
    post 'downvote'
  end

  namespace :api do
    namespace :v1 do
      resources :review_votes do
        post 'upvote'
        post 'downvote'
      end
    end
  end

end

app/views/layouts/_recent_parks.html.erb
<li><%= link_to "#{park.name}", park_path(park) %></li>

app/views/layouts/_recent_reviews.html.erb
<li><%= link_to "#{review.title}", park_path(review.park) %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>National Parks Review</title>
    <link rel="shortcut icon" href="https://s3.amazonaws.com/national-park-reviews-development/my_site.ico">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

  </head>

  <body>
    <div class="top-bar">
      <div class="top-bar-left">
        <ul class="menu">
          <li class="menu-text">National Park Reviews</li>
        </ul>
      </div>

      <div class="top-bar-right">
        <ul class="menu">
          <% if signed_in? %>
          <li><%= link_to "#{current_user.email}", user_path(current_user) %></li>
          <li><%= link_to "Add a Park", new_park_path %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, data: { method: 'delete' } %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <!-- End Top Bar -->

    <div class="row column text-center">
      <div class="callout large primary" id="banner-container">
        <%= image_tag 'https://s3.amazonaws.com/national-park-reviews-development/page_photos/park_banner.jpg',
        class: "banner-image"%>
      </div>
    </div>

    <div class="row" id="content">
      <% if flash[:notice] || flash[:alert] %>
        <div class="callout">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
      <% end %>

      <br>

      <div class="medium-8 columns">
        <%= yield %>
      </div>

      <% if controller.lookup_context.prefixes[0] == "parks" %>
        <div class="medium-4 columns" data-sticky-container>
          <div class="sticky is-anchored" data-sticky data-top-anchor="root:content">
            <%= form_tag(parks_path, method: "get") do %>
              <%= label_tag(:search_terms, "Search Parks:") %>
              <%= text_field_tag(:search_terms) %>
              <%= submit_tag("Search") %>
            <% end %>

            <h4>Recently Added Parks</h4>
            <ul>
              <%= render partial: "layouts/recent_parks", collection: @recent_parks, as: :park %>
            </ul>
            <h4>Recent Reviews</h4>
            <ul>
              <%= render partial: "layouts/recent_reviews", collection: @recent_reviews, as: :review %>
            </ul>
          </div>
        </div>
      <% else %>
        <div class="medium-4 columns" data-sticky-container>
          <!-- blank div to maintain spacing -->
        </div>
      <% end %>
      <!-- End sidebar -->

    </div>

  </body>
</html>

app/views/layouts/application_backup.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>National Parks Review</title>
    <link rel="shortcut icon" href="https://s3.amazonaws.com/national-park-reviews-development/my_site.ico">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if signed_in? %>
      <%= link_to "#{current_user.email}", user_path(current_user) %> |
      <%= link_to "Add a Park", new_park_path %> |
      <%= link_to "Sign out", destroy_user_session_path, data: { method: 'delete' } %>
    <% else %>
      <%= link_to "Sign in", new_user_session_path %>
      <%= link_to "Sign up", new_user_registration_path %>
    <% end %><br><br>

    <%= form_tag(parks_path, method: "get") do %>
      <%= label_tag(:search_terms, "Search Parks:") %>
      <%= text_field_tag(:search_terms) %>
      <%= submit_tag("Search") %>
    <% end %>

    <%= yield %>
  </body>
</html>